version: "3"
services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - mynetwork

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - mynetwork

  client:
    container_name: client
    restart: always
    ports:
      - "8080:8080"
    build:
      context: ../corporate-messenger-web-client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - mynetwork

  gateway:
    container_name: gateway
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres:
  pgadmin:
