version: "3"
services:
#  main:
#    container_name: server
#    build:
#      context: .
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    env_file:
#      - .env
#    ports:
#      - "${PORT}:${PORT}"
#      - "9229:9229"
#    depends_on:
#      - redis
#      - postgres

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - docker.env

volumes:
  postgres:
  pgadmin:
